apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjobtest
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: jobtest
            image: pripodsampleapp:debug
          restartPolicy: Never